services:
  webapp:
    container_name: iu-project-cc-webapp
    build: "./web-app"
    ports:
      - "8080:80"
  
  backend:
    container_name: iu-project-cc-backend
    build: "./backend"
    depends_on:
      - database
    ports:
      - "9090:3000"
    environment:
      - DYNAMODB_TABLE_TRAVEL_GUIDES=TravelGuides
      # Configure usage of DynamoDB Local
      - USE_DYNAMODB_LOCAL=true
      - DYNAMODB_LOCAL_URL=http://iu-project-cc-dynamodb:8000
      # Configure Mock-Credentials for DynamoDB Local
      - AWS_ACCESS_KEY_ID=XXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXX
  
  database:
    container_name: iu-project-cc-dynamodb
    image: "amazon/dynamodb-local:2.6.1"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./.storage/dynamodb/data:/home/dynamodblocal/data"
