namePrefix: prod-
commonLabels:
  environment: prod
namespace: prod-travel-guides

bases:
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: backend-env-patch.yaml
