apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "travel-guides-stage"
spec:
  destination:
    namespace: stage-travel-guides
    server: https://kubernetes.default.svc
  source:
    path: kubernetes/overlays/stage
    repoURL: https://github.com/marcelfrey29/IU-DOCC-Project-Container-Orchestration
    targetRevision: argocd_stage
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
