# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Kubernetes CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - kubernetes/**
      - .github/workflows/k8s-ci.yml
  workflow_dispatch: 
  workflow_call:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Check Kustomize Generation for Stage
        run: kubectl kustomize kubernetes/overlays/stage 
      - name: Check Kustomize Generation for Prod
        run: kubectl kustomize kubernetes/overlays/prod

  kube-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Kube-Lint
        uses: stackrox/kube-linter-action@v1
        with:
          directory: kubernetes

  sast-trivy-repo-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH'
          scan-ref: 'kubernetes'
          exit-code: '1'
          format: 'table'
          trivyignores: '.trivyignore'
